---
title: "CentralPark, NY Visualization"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)

```

```{r, include = FALSE}
modified_noaa = data.frame(ny_noaa) %>% 
  filter(id == "USW00094728") %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("year", "month", "day"), sep = "-") %>% 
  janitor::clean_names() %>%
  mutate(id =as.factor(id),
         year = as.numeric(year), 
         month = as.numeric(month),
         day = as.numeric(day),
         prcp = as.numeric(prcp)/10,
         snow = as.numeric(snow),
         snwd = as.numeric(snwd),
         tmax = as.numeric(tmax)/10, 
         tmin = as.numeric(tmin)/10)
# Filter id == "USW00094728", which is data for Central_park_NY, adjust the unit for some variables 

prcp_data = modified_noaa %>%
  select(year, prcp) %>% 
  mutate(prcp = as.numeric(prcp > 0)) %>% 
  # when prcp is greater than 0, count it.
  group_by(year, prcp) %>% 
  summarize(count = n()) %>%
  # get the count of prcp days of one year
  filter(prcp == 1)
## This dataset is about precpitation. I am interested in number of days have precpitation of one year. 
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A- tmax VS. tmin in Central Park, NY

```{r}
modified_noaa %>%
  plot_ly(x = ~tmin, y = ~tmax, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~month)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B - Boxplot of tmax across months

```{r}
modified_noaa %>%
  plot_ly(y = ~tmax, x = ~ month, type = "box", colors = "Set2")
```

### Chart C - No.days having precpitation each year

```{r}

plot_ly(prcp_data, x = ~year, y = ~count, type = 'bar') %>% 
  layout(yaxis = list(title = 'No. of day prcp'))

```

